### ISSUE TITLE
Import from clipboard fails for some lirc files

### ISSUE THREAD

**Issue by irplus-remote** [bengtmartensson/harctoolboxbundle#241]
This is a valid lirc file generated with irrecord

Copy paste -> Load from clipboard causes this error:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: comment must be non-zero, (can be empty).
	at org.harctoolbox.irscrutinizer.NamedIrSignal.<init>(NamedIrSignal.java:61)
	at org.harctoolbox.irscrutinizer.RawIrSignal.<init>(RawIrSignal.java:56)
	at org.harctoolbox.irscrutinizer.RawIrSignal.<init>(RawIrSignal.java:61)
	at org.harctoolbox.irscrutinizer.GuiMain.registerRawCommand(GuiMain.java:1404)
	at org.harctoolbox.irscrutinizer.GuiMain.importCommand(GuiMain.java:1317)

```


# Please take the time to finish this file as described in
# https://sourceforge.net/p/lirc-remotes/wiki/Checklist/
# and make it available to others by sending it to
# <lirc@bartelmus.de>
#
# This config file was automatically generated
# using lirc-0.9.4c(default) on Tue Jul  3 11:21:44 2018
# Command line used: -n -f -d /dev/lirc0
# Kernel version (uname -r): 4.14.34-v7+
#
# Remote name (as of config file): kkk
# Brand of remote device, the thing you hold in your hand:
# Remote device model nr:
# Remote device info url:
# Does remote device has a bundled capture device e. g., a
#     usb dongle? :
# For bundled USB devices: usb vendor id, product id
#     and device string (use dmesg or lsusb):
# Type of device controlled
#     (TV, VCR, Audio, DVD, Satellite, Cable, HTPC, ...) :
# Device(s) controlled by this remote:

begin remote

  name  kkk
  flags RAW_CODES|CONST_LENGTH
  eps            30
  aeps          100

  gap          108329

      begin raw_codes

          name portal
             9031    4524     541     599     542     599
              573     544     597     544     568     572
              541     599     546     572     596     544
              569     572     543    1741     569    1684
              569    1717     568     572     541    1712
              571    1714     550     590     542     599
              541     576     569     575     565     572
              541    1717     541     599     596    1685
              545     600     568    1685     569    1711
              547    1712     568    1713     568     572
              541    1744     542     571     569    1740
              513

          name info
             9022    4514     596     540     596     535
              597     540     591     540     564     573
              618     540     596     535     629     481
              591     567     596    1671     569    1699
              591    1676     619     512     596    1672
              651    1643     592     540     596     535
              596    1671     624    1644     595    1672
              568     590     597     539     542     590
              541     595     564    1699     624     512
              623     508     596     541     595    1667
              683    1588     624    1644     564    1726
              596

          name media
             9013    4502     540     604     568     545
              573     572     596     572     568     549
              597     520     565     549     624     544
              569     599     545    1685     546    1740
              573    1685     597     520     569    1717
              624    1657     600     545     569    1689
              596    1685     573    1690     596     544
              569     576     624     544     541     549
              569     572     597     543     519     627
              601     516     564    1722     563    1717
              573    1685     569    1717     600    1657
              569

          name blue
             5169     307    1379     361     775     306
              166     333     166    4579     326     833
              482     622     542     622     491     700
              399     649     537     622     198     910
              537     677     138    1213     239    1808
              459    1758     428    1869     163    1017
              166    2048     458    2047     111     813
               85     190     180     786     271    1992
              303    3017     112    2128     112    1051
               85

          name exit
             8983    4548     566     567     513     655
              431     733     459     630     537     600
              567     573     597     545     563     545
              462     680     511    1743     533    1770
              507    1745     538     624     508    1767
              519    1737     511     630     534    1746
              532    1739     515    1739     563    1714
              571     512     738     425     541     602
              541     625     542     567     595     576
              565     572     539     597     514    1714
              565    1768     539    1708     512    1743
              537

          name portal2
              448     306    4641     292     198     301
              193     306     111     764     605     306
              249    4789     197     961     111     283
              111     627      83

          name txt
             8921    4743     138     833     496     773
              244     787     348     783     463     645
              197     966     459     727     111     997
              166     915     537    1762     348    4241
              138     997     308    1932     166

      end raw_codes

end remote


```

**Comment by bengtmartensson** [comment]
Thank you for the report.

Sorry, I cannot reproduce with the latest snapshot, nor with the official 1.4.1.  If you are using a snapshot other than the latest, please update to the latest.

Also adding more lines to the stackdump might help.

PS. Why are you using irrecord when you have IrScrutinizer? Have you discovered the /dev/lirc support?

**Comment by irplus-remote** [comment]
You're on Linux right? Hm Maybe i need to update the snapshot :/ Will check. With 1.4.1 it works!

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: comment must be non-zero, (can be empty).
	at org.harctoolbox.irscrutinizer.NamedIrSignal.<init>(NamedIrSignal.java:61)
	at org.harctoolbox.irscrutinizer.ParametrizedIrSignal.<init>(ParametrizedIrSignal.java:82)
	at org.harctoolbox.irscrutinizer.GuiMain.registerParameterCommand(GuiMain.java:1408)
	at org.harctoolbox.irscrutinizer.GuiMain.importCommand(GuiMain.java:1319)
	at org.harctoolbox.irscrutinizer.GuiMain.importCommands(GuiMain.java:1296)
	at org.harctoolbox.irscrutinizer.importer.TreeImporter.importAllButtonActionPerformed(TreeImporter.java:476)
	at org.harctoolbox.irscrutinizer.importer.TreeImporter.access$900(TreeImporter.java:47)
	at org.harctoolbox.irscrutinizer.importer.TreeImporter$9.actionPerformed(TreeImporter.java:366)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by irplus-remote** [comment]
probably it's really a windows-thing.

BTW im using irrecord, because the IR-receiver is on a Rpi, and irscrutinizer doesnt run properly on it (veeery slow :) ) 

![image](https://user-images.githubusercontent.com/14196521/42265245-45b9f51a-7f73-11e8-9f38-3b4779aee867.png)

**Comment by bengtmartensson** [comment]
Please do the following:
first confirm that the problem does occur with the latest snapshot (as I cannot reproduce). If so, save your problematic clipboard to a file, confirm that loading the file triggers the same problem, and assuming so, upload it as a gist etc.

> probably it's really a windows-thing 

Very unlikely, unless it has something to do with the clipboard.

> BTW im using irrecord, because the IR-receiver is on a Rpi, and irscrutinizer doesnt run properly on it (veeery slow :) )

For me, with RPi 3, it takes half a minute to start, but then it is OK. Different for you? If you have a reproducible problem, please open a ticket.

**Comment by irplus-remote** [comment]
It doesnt depend on the clipboard, even when i save the file it happens!
[file.txt](https://github.com/bengtmartensson/harctoolboxbundle/files/2165368/file.txt)

Using latest snapshot

**Comment by irplus-remote** [comment]
By the way i've now installed irscrutinizer on the pi again, and it happens there too with this file!
Using: https://github.com/bengtmartensson/harctoolboxbundle/releases

**Comment by bengtmartensson** [comment]
> Note that you have to click on "import all" for the error to happen

Ok, _that_ was the magic word! Thanx for the bug report. Please try the new current snapshot.

I also look forward to you feedback on capturing signals with IrScrutinizer on the RPi.
